<script lang="ts">
    import Button from "../../lib/Button.svelte";
    import EditQuestion from "../../lib/edit/EditQuestion.svelte";
    import EditSidebar from "../../lib/edit/EditSidebar.svelte";
    import type { Quiz, QuizQuestion } from "../../model/quiz";
    import { apiService } from "../../service/api";

    let quiz: Quiz = {
        id: '', // This will be generated by the backend
        name: '',
        questions: []
    };
    let selectedQuestion: QuizQuestion | null = null;

    function onQuestionDelete() {
        quiz.questions = quiz.questions.filter(
            (q) => q.id != selectedQuestion?.id,
        );
        selectedQuestion = null;
    }

    async function save() {
        if (quiz == null) return;

        const newQuiz = await apiService.createQuiz(quiz);
        if (newQuiz) {
            quiz = newQuiz;
            // Optionally, navigate to the edit page for the new quiz
        }
    }
</script>

<div class="bg-gray-100 w-full p-2 flex justify-end">
    <div class="flex gap-2">
        <input
            type="text"
            class="border rounded px-2"
            placeholder="Quiz name"
            bind:value={quiz.name}
        />
        <Button on:click={save}>Save</Button>
    </div>
</div>
<div class="flex">
    <EditSidebar bind:questions={quiz.questions} bind:selectedQuestion />
    {#if selectedQuestion != null}
        <EditQuestion
            on:delete={onQuestionDelete}
            on:change={() => quiz = quiz}
            bind:selectedQuestion
        />
    {/if}
</div>